
kind: Service
apiVersion: v1
metadata:
  name: influxdb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
  selector:
    app: influxdb
  clusterIP: None