
kind: Service
apiVersion: v1
metadata:
  name: php-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: php
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 80
  
