kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None